schema_version = "1.0.0"

id = "Playbook"
version = "1.0.1"
name = "Playbook Diffusion Based Renderer"
tagline = "Playbook is a diffusion based engine for 3D scenes"
maintainer = "<support@playbook3d.com>"
type = "add-on"

website = "https://www.playbook3d.com"

blender_version_min = "4.0.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "Playbook 3D 2024",
]

network = "Need to connect to ComfyUI"
files = "Import/export renders from/to disk"
